# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - my-postgresql:/var/lib/postgresql/data

volumes:
  my-postgresql:        
    name: my-postgresql